# Generated by Django 6.0 on 2026-01-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Genre', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ANIMATION', 'Animation'), ('BIOGRAPHY', 'Biography'), ('COMEDY', 'Comedy'), ('COMING_OF_AGE', 'Coming of Age'), ('CRIME', 'Crime'), ('CYBERPUNK', 'Cyberpunk'), ('DARK_COMEDY', 'Dark Comedy'), ('DOCUMENTARY', 'Documentary'), ('DRAMA', 'Drama'), ('FAMILY', 'Family'), ('FANTASY', 'Fantasy'), ('HISTORICAL', 'Historical'), ('HORROR', 'Horror'), ('MUSIC', 'Music'), ('MYSTERY', 'Mystery'), ('POST_APOCALYPTIC', 'Post-Apocalyptic'), ('ROMANCE', 'Romance'), ('ROMANTIC_COMEDY', 'Romantic Comedy'), ('SCI_FI', 'Science Fiction'), ('SUPERHERO', 'Superhero'), ('SURVIVAL', 'Survival'), ('THRILLER', 'Thriller'), ('TIME_TRAVEL', 'Time Travel'), ('WAR', 'War'), ('WESTERN', 'Western')], max_length=30)),
                ('Released_date', models.DateField()),
                ('Content_category', models.CharField(choices=[('MOVIES', 'Movies'), ('SERIES', 'Series'), ('DOCUMENTARY', 'Documentary'), ('ANIMATION', 'Animation'), ('KIDS', 'Kids'), ('SPORTS', 'Sports')])),
                ('Content_description', models.TextField()),
                ('Duration_in_minutes', models.PositiveIntegerField()),
                ('Ratings', models.IntegerField(default=1)),
                ('Starcasts', models.TextField()),
                ('Director', models.CharField(max_length=50)),
                ('Producer', models.CharField(max_length=50)),
                ('Audiences', models.CharField(choices=[('G', 'General Audience'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only'), ('ALL', 'All Ages'), ('KIDS', 'Kids'), ('TEEN', 'Teen'), ('ADULT', 'Adult')])),
                ('Thumbnail', models.URLField()),
                ('Video', models.URLField()),
                ('Trailer', models.URLField()),
            ],
        ),
    ]
