# Generated by Django 6.0 on 2026-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='Userotp',
            field=models.IntegerField(),
        ),
    ]
