# Generated by Django 6.0 on 2026-01-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_order_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Subscription_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ELITE', 'Elite')], max_length=20),
        ),
    ]
