# Generated by Django 6.0 on 2026-01-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_plan_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
