CONTENT_CHOICES = (
    ("MOVIES", "Movies"),
    ("SERIES", "Series"),
    ("DOCUMENTARY", "Documentary"),
    ("ANIMATION", "Animation"),
    ("KIDS", "Kids"),
    ("SPORTS", "Sports"),
)

RATING_CHOICES = (
    ("G", "General Audience"),
    ("PG", "Parental Guidance Suggested"),
    ("PG-13", "Parents Strongly Cautioned"),
    ("R", "Restricted"),
    ("NC-17", "Adults Only"),
    ("ALL", "All Ages"),
    ("KIDS", "Kids"),
    ("TEEN", "Teen"),
    ("ADULT", "Adult"),
)

GENRE_CHOICES = (
    ("ACTION", "Action"),
    ("ADVENTURE", "Adventure"),
    ("ANIMATION", "Animation"),
    ("BIOGRAPHY", "Biography"),
    ("COMEDY", "Comedy"),
    ("COMING_OF_AGE", "Coming of Age"),
    ("CRIME", "Crime"),
    ("CYBERPUNK", "Cyberpunk"),
    ("DARK_COMEDY", "Dark Comedy"),
    ("DOCUMENTARY", "Documentary"),
    ("DRAMA", "Drama"),
    ("FAMILY", "Family"),
    ("FANTASY", "Fantasy"),
    ("HISTORICAL", "Historical"),
    ("HORROR", "Horror"),
    ("MUSIC", "Music"),
    ("MYSTERY", "Mystery"),
    ("POST_APOCALYPTIC", "Post-Apocalyptic"),
    ("ROMANCE", "Romance"),
    ("ROMANTIC_COMEDY", "Romantic Comedy"),
    ("SCI_FI", "Science Fiction"),
    ("SUPERHERO", "Superhero"),
    ("SURVIVAL", "Survival"),
    ("THRILLER", "Thriller"),
    ("TIME_TRAVEL", "Time Travel"),
    ("WAR", "War"),
    ("WESTERN", "Western"),
)
